// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUd1_-9XxNY2JQ_Dg55dB4E-JYAenMbx0',
    appId: '1:574241783418:web:aa0c04869d57bbe02185c3',
    messagingSenderId: '574241783418',
    projectId: 'mapx-007',
    authDomain: 'mapx-007.firebaseapp.com',
    storageBucket: 'mapx-007.firebasestorage.app',
    measurementId: 'G-Y5EVXMX3F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwXXOVlhzYF1OkezTr3eomYDLeR6fPpIw',
    appId: '1:574241783418:android:46f120e288e13c232185c3',
    messagingSenderId: '574241783418',
    projectId: 'mapx-007',
    storageBucket: 'mapx-007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhKCLTz10neSnoiE7rv4E6ebBMwJVPqd8',
    appId: '1:574241783418:ios:41a6145a1b4d82e02185c3',
    messagingSenderId: '574241783418',
    projectId: 'mapx-007',
    storageBucket: 'mapx-007.firebasestorage.app',
    iosBundleId: 'com.example.mapx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhKCLTz10neSnoiE7rv4E6ebBMwJVPqd8',
    appId: '1:574241783418:ios:41a6145a1b4d82e02185c3',
    messagingSenderId: '574241783418',
    projectId: 'mapx-007',
    storageBucket: 'mapx-007.firebasestorage.app',
    iosBundleId: 'com.example.mapx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUd1_-9XxNY2JQ_Dg55dB4E-JYAenMbx0',
    appId: '1:574241783418:web:8e959d0b777d13862185c3',
    messagingSenderId: '574241783418',
    projectId: 'mapx-007',
    authDomain: 'mapx-007.firebaseapp.com',
    storageBucket: 'mapx-007.firebasestorage.app',
    measurementId: 'G-FZ086Q3HWK',
  );
}
